employees/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EmployeeListView.as_view(), name='employees'),
    path('<int:pk>/', views.EmployeeDetailView.as_view(), name='employee'),
    path('search/', views.SearchEmployeeListView.as_view(), name='search')
]

urker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse_lazy
from .views import logout_view
from employees.views import EmployeeListView

admin.site.site_url = reverse_lazy('employees')
admin.site.site_header = 'Urker admin'
admin.site.site_title = 'Urker admin'
admin.site.index_title = 'Urker administration'
admin.empty_value_display = '**Empty**'
admin.site.logout = logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),
    path('logout/', logout_view, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

certificates/models.py
from django.db import models
from employees.models import Employee


class Certificate(models.Model):

    certificate = models.FileField(upload_to="certificates/")
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return self.employee.name


class Resume(models.Model):

    resume = models.FileField(upload_to="resumes/")
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return self.employee.name


class Education(models.Model):

    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    date_finished = models.CharField(max_length=200)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

complaints/models.py
from django.db import models
from employees.models import Employee


class Complaint(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    reason = models.TextField()
    date_register = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(verbose_name='is good?')

    def __str__(self):
        return self.employee.name

employees/models.py
from django.db import models
from datetime import datetime
from _decimal import ROUND_DOWN
from decimal import Decimal

class Position(models.Model):
    position = models.CharField(max_length=200)

    def __str__(self):
        return self.position


class Employee(models.Model):
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=200)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False, verbose_name="Is it active?")
    image = models.ImageField(upload_to='employee/year-%Y/month-%m/day-%d', blank=True)
    about = models.TextField(verbose_name="History")
    birthday = models.DateField(blank=True, null=True)
    address = models.CharField(blank=True, max_length=200, null=True)
    hire_date = models.DateField(default=datetime.now)

    @property
    def zero_id(self):
        id = f'{self.id:05}'
        return id

    @property
    def age(self):
        import datetime
        return int((datetime.date.today() - self.birthday).days / 365.25)

    @property
    def rating_count(self):
        rating = 10
        plus = self.complaint_set.filter(status=True).count() * Decimal('0.2').quantize(Decimal('.1'), rounding=ROUND_DOWN)
        minus = self.complaint_set.filter(status=False).count() * Decimal('0.2').quantize(Decimal('.1'), rounding=ROUND_DOWN)

        rating -= minus
        rating += plus

        if rating > 10.0:
            rating = 10.0

        if rating <= 0.0:
            self.is_active = False

        return rating

    def __str__(self):
        return f'{self.id:05}' + " - " + self.name.title() + " " + self.surname.title()

certificates/views.py
from django.shortcuts import render

# Create your views here.

complaints/views.py
from django.shortcuts import render

# Create your views here.

employees/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Q
from .models import Employee


class EmployeeListView(ListView):
    queryset = Employee.objects.filter(is_active=True)
    template_name = 'employee/employee_list.html'
    context_object_name = 'employees'


class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'employee/employee_detail.html'


class SearchEmployeeListView(ListView):
    template_name = 'employee/employee_list.html'
    context_object_name = 'employees'

    def get_context_data(self, *args, **kwargs):
        context = super(SearchEmployeeListView, self).get_context_data(*args, **kwargs)
        context["query"] = self.request.GET.get('q')
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')
        if query is not None:
            lookups = Q(id__icontains=query) | Q(name__icontains=query) | Q(surname__icontains=query) | Q(position__position__icontains=query)
            return Employee.objects.filter(lookups).distinct()
        return Employee.objects.none()

urker/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy


# class UserLoginView(LoginView):
#     template_name = 'accounts/login.html'
#     success_url = reverse_lazy('user_profile')


def logout_view(request):
    logout(request)
    return redirect('employees')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Urker</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Icon css link -->
    <link href="{% static 'vendors/material-icon/css/materialdesignicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/linears-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'vendors/owl-carousel/assets/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/animate-css/animate.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

{##}
    <link href="{% static 'css/footer-distributed-with-address-and-phones.css' %}" rel="stylesheet">

    <link href="{% static 'css/search.css' %}" rel="stylesheet">


    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
</head>
<body class="dark_bg" data-spy="scroll" data-target="#bs-example-navbar-collapse-1" data-offset="80" data-scroll-animation="true">

        <!--================ Frist hader Area =================-->
        <header class="header_area">
            <div class="container">
                <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'employees' %}"><img src="{% static 'img/urker_logo.png' %}" alt="" width="150"></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active">
                                <form action="{% url 'search' %}">
                                    <div class="flexbox">
                                      <div class="search">
                                        <div>
                                          <input name="q" type="text" placeholder="       Search . . ." required>
                                        </div>
                                      </div>
                                    </div>
                                </form>
                            </li>
                            <li class="active"><a href="{% url 'employees' %}">Employees</a></li>
                            {% if user.is_authenticated %}
                                <li class="active"><a href="{% url 'admin:index' %}">Admin Panel</a></li>
                                <li class="active"><a href="{% url 'logout' %}">Log out</a></li>
                            {% else %}
                                <li class="active"><a href="{% url 'admin:index' %}">Log in</a></li>
                            {% endif %}
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </div>
        </header>


            {% block content %}
            {% endblock %}

        <footer class="footer-distributed">

			<div class="footer-left">

				<h3><span class="logo">URKER</span></h3>


				<p class="footer-company-name">All rights reserved &copy2019</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>Sultan Beibarys, 510</span> Kazakhstan, Atyrau</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>8-(777)-599-57-45</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p>urker@gmail.com</p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the company</span>
					URKER GROUP представляет полный спектр электромонтажных работ и установку контрольно-измерительных приборов и автоматики любой сложности, начиная с поставки необходимых материалов, оборудований и заканчивая пуско-наладочными работами и сдачей объект под ключ.
				</p>


			</div>

		</footer>


    <script src="{% static 'js/cards.js' %}"></script>
    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/counter-up/waypoints.min.js' %}"></script>
    <script src="{% static 'vendors/counter-up/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>

    <script src="{% static 'vendors/style-switcher/styleswitcher.js' %}"></script>
    <script src="{% static 'vendors/style-switcher/switcher-active.js' %}"></script>

    <script src="{% static 'vendors/animate-css/wow.min.js' %}"></script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'js/gmaps.min.js' %}"></script>

    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
{#    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>#}
{#    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>#}
</body>
</html>

templates/employee/employee_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <!--================Total container Area =================-->
    <div class="container main_container">
        <div class="content_inner_bg row m0">
            <section class="about_person_area pad" id="about">
                <div class="row">
                    <div class="col-md-5">
                        <div class="person_img">
                            {% if object.image %}
                                <img src="{{ object.image.url }}" alt="{{ object.name }} {{ object.surname }}">
                            {% else %}
                                <img src="{% static 'img/default_user.png' %}">
                            {% endif %}
                            <a class="download_btn" href="{{ object.resume.resume.url }}" download><span>Download Resume</span></a>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="row person_details">
                            <h3><span>{{ object.name }} {{ object.surname }}</span></h3>
                            <h4>{{ object.position }}</h4>
                            <p>{{ object.about|linebreaks }}</p>
                            <div class="person_information">
                                <ul>
                                    <li>ID</li>
                                    <li>Age</li>
                                    <li>Address</li>
                                    <li>Phone</li>
                                    <li>Email</li>
                                    <li>Birth date</li>
                                    <li>Work experience time</li>
                                    {% if user.is_superuser %}
                                        <li>Rating</li>
                                    {% endif %}
                                </ul>
                                <ul>
                                    <li>{{ employee.zero_id }}</li>
                                    <li>{{ employee.age }}</li>
                                    <li>{{ employee.address }}</li>
                                    <li>{{ object.mobile_number }}</li>
                                    <li>{{ object.email }}</li>
                                    <li>{{ object.birthday }}</li>
                                    <li>{{ object.hire_date|timesince }}</li>
                                    {% if user.is_superuser %}
                                        <li>{{ employee.rating_count }}</li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {% if object.education_set.all %}
                <section class="education_area pad" id="education">
                <div class="main_title">
                    <h2>Education</h2>
                </div>
                <div class="education_inner_area">
                    {% for edu in object.education_set.all %}
                        <div class="education_item wow fadeInUp animated" data-line="O">
                            <h6>{{ edu.date_finished }}</h6>
                            <h4>{{ edu.name }}</h4>
                            <h5>{{ edu.address }}</h5>
                            {% if edu.description %}
                                <p>{{ edu.description }}</p>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </section>
            {% endif %}
            {% if object.certificate_set.all %}
                <section class="portfolio_area pad" id="portfolio">
                <div class="main_title">
                    <h2>Progress</h2>
                </div>
                <div class="row">
                    <div class="portfolio_list_inner">
                        {% for certificate in object.certificate_set.all %}
                            <div class="col-md-4 photo marketing">
                                <div class="portfolio_item">
                                    <div class="">
                                        <embed src="{{ certificate.certificate.url }}" width="314px" height="392px" />
                                    </div>
                                    <div class="portfolio_title mb-4">
                                        <a href="{{ certificate.certificate.url }}"><h4>See more</h4></a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
            {% endif %}

        </div>
    </div>
    <!--================End Total container Area =================-->



    {% if user.is_superuser and object.complaint_set.all %}
        <div class="container mt-3">
            <div class="row">
                <div class="col-md-12">
                    <div class="twitter_area wow fadeInLeft  animated" style="visibility: visible; animation-name: fadeInLeft;">
                        <div class="w_title">
                            <h3>Complaints</h3>
                        </div>
                        <ul class="text-center">
                            {% for complaint in object.complaint_set.all %}
                                <li><h4 class="{% if complaint.status %} text-success {% else %} text-danger {% endif %}">{{ complaint.reason }}</h4><br> <div class="text-right">{{ complaint.date_register }}</div></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}

templates/employee/employee_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    <!--================Total container Area =================-->
    <div class="container main_container">
        <div class="content_inner_bg row m0">
            <section class="about_person_area pad" id="about">
                <div class="row">
                    {% for employee in employees %}
                    <div class="col-md-4 col-sm-6">
                        <!-- Card widget -->
                        <div class="card">
                          <div class="card-face face-1">
                              <a href="{% url 'employee' employee.id %}"><h2 class="card-body">{{ employee.zero_id }}</h2></a>
                              <a href="{% url 'employee' employee.id %}"><div class="card-face__avatar">{% if employee.image %} <img src="{{ employee.image.url }}" draggable="false" width="300" height="400"/> {% endif %}</div></a>
                              <a href="{% url 'employee' employee.id %}"><h3 class="card-face__title">{{ employee.name }} {{ employee.surname }}</h3></a>
                               <div class="person_information">
                                <ul>
                                    <li>Position: {{ employee.position }}</li>
                                    <li>Work experience time: {{ employee.hire_date|timesince }}</li>
                                </ul>
                            </div>
                          </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </section>

        </div>
    </div>

{% endblock %}